[project]
name = "deeprlwebplayground-backend"
version = "0.1.0"
dependencies = [
    "torch",
    "numpy",
    "wandb",
    "gymnasium[atari,accept-rom-license]==0.29.1",
    "opencv-python",
    "shimmy>=0.2.1",
]

[tool.setuptools]
packages = ["backend", "NodeLib"]
package-dir = {"backend" = ".", "NodeLib" = "Utils/src/NodeLib"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"