[project]
name = "SignalFlowRL"
version = "1.0.0"
dependencies = [
    "torch",
    "numpy",
    "wandb",
   "gymnasium[atari,accept-rom-license,mujoco]==0.29.1",
    "opencv-python",
    "shimmy>=0.2.1",
    "python-dotenv",
]

[tool.setuptools]
packages = ["NodeLib"]
package-dir = {"NodeLib" = "Utils/src/NodeLib" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"