import unittest
from unittest.mock import MagicMock
import torch

from backend.utils import ReplayBuffer
from backend.T3D.src.TD3_Trainer import TD3_Trainer

class TestTD3Trainer(unittest.TestCase):
    def setUp(self):
        self.state_size = 6 #TODO: These are autogenerated by PyCharm, adapt them to the values from the paper later although it should not matter
        self.hidden_size = 5
        self.action_size = 64
        self.max_action = 1.0
        self.learning_rate = 1e-3
        self.tau = 0.005
        self.noise_clip = 0.2
        self.policy_noise = 0.1
        self.batch_size = 32

        self.trainer = TD3_Trainer(
            state_size=self.state_size,
            action_size=self.action_size,
            hidden_size=self.hidden_size,
            max_action=self.max_action,
            learning_rate=self.learning_rate,
            tau=self.tau,
            noise_clip=self.noise_clip,
            policy_noise=self.policy_noise
        )

        self.mock_buffer = MagicMock(spec=ReplayBuffer)
        self.mock_buffer.sample.return_value = (
            torch.randn(self.batch_size, self.state_size),
            torch.randn(self.batch_size, self.action_size),
            torch.randn(self.batch_size, self.state_size),
            torch.randn(self.batch_size, 1),
            torch.ones(self.batch_size, 1)
        )

    def test_updates_critics(self):
        # Save initial critic weights
        initial_critic_1_weights = [p.clone() for p in self.trainer.critic_1.parameters()]
        initial_critic_2_weights = [p.clone() for p in self.trainer.critic_2.parameters()]

        self.trainer.train(self.mock_buffer, batch_size=self.batch_size)

        # TODO: We can probably get more specific than this, more concrete init with known weights and the influence of a known update
        for p_old, p_new in zip(initial_critic_1_weights, self.trainer.critic_1.parameters()):
            self.assertFalse(torch.equal(p_old, p_new))

        for p_old, p_new in zip(initial_critic_2_weights, self.trainer.critic_2.parameters()):
            self.assertFalse(torch.equal(p_old, p_new))

    def test_actor_update(self):

        self.trainer.current_episode = self.trainer.syncro_frequency - 1

        initial_actor_weights = [p.clone() for p in self.trainer.actor.parameters()]
        initial_target_weights = [p.clone() for p in self.trainer.actor_target.parameters()]

        self.trainer.train(self.mock_buffer, batch_size=self.batch_size)

        for p_old, p_new in zip(initial_actor_weights, self.trainer.actor.parameters()):
            self.assertFalse(torch.equal(p_old, p_new))

        for p_old, p_new in zip(initial_target_weights, self.trainer.actor_target.parameters()):
            self.assertFalse(torch.equal(p_old, p_new))

if __name__ == "__main__":
    unittest.main()