import time
from copy import deepcopy

import torch
import wandb
from torch import nn

from backend.ActionValue.DQN.src.ActionHandler import EpsilonGreedyPolicy
from backend.ActionValue.DQN.src.DataCollectionProcessor import DataCollectionProcessor
from backend.ActionValue.DQN.src.TrainProcessor import TrainProcessor
from backend.Utils.src.BatchTransitioner import TransitionSpec, TransitionFactory
from backend.Utils.src.EnvFactory import GymEnvFactory
from backend.Utils.src.EnviromentHandler import EnvironmentHandler
from backend.Utils.src.ReplayBuffer import ReplayBuffer
from backend.Utils.src.SyncProcessor import SyncProcessor

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def evaluate_policy(policy, env_handler, episodes=5, device="cpu"):
    """
   Eval Function Generated by UNi LLM To be deleted later
    """
    policy.eval()
    total_reward = 0.0

    for _ in range(episodes):
        state = env_handler.reset()
        done = False
        episode_reward = 0.0
        steps = 0

        while not done:
            state_tensor = torch.tensor(state, device=device).unsqueeze(0).float()
            with torch.no_grad():
                q_values = policy(state_tensor)
                action = torch.argmax(q_values, dim=1).item()

            next_state, reward, done, _ = env_handler.step(action)
            episode_reward += reward
            state = next_state
            steps += 1

        total_reward += episode_reward

    policy.train()
    return total_reward / episodes

def main():
    # initialization
    start_time = time.time()
    lr = 2.5e-4
    epsilon = 1.0
    env_name = "CartPole-v1"
    sync_freq = 1000
    hidden_size = 120
    batch_size = 128
    max_buffer_size = 100_000
    tau = 1.0
    gamma = 0.99
    max_steps = 1000000
    max_norm = 5
    spec = TransitionSpec(["state", "action", "reward", "next_state", "done"])
    gym_factory = GymEnvFactory(env_name)
    factory = TransitionFactory(spec)
    seed = 1
    warmup_steps = 10000

    wandb.init(
        entity="michael_dohmen-",
        project="my-dqn-benchmarks",
        config={
            "env_id": env_name,
            "exp_name": "DQN-CartPole-v1",
            "seed": seed,
            "max_buffer_size": max_buffer_size,
            "batch_size": batch_size,
            "max_steps": max_steps,
            "lr": lr,
            "gamma": gamma,
            "sync_freq": sync_freq,
            "warmup_steps": warmup_steps,
            "max_norm": max_norm,
            "epsilon": epsilon,
            "tau": tau,
        }
    )

    env = EnvironmentHandler(gym_factory, seed)
    eval_env = EnvironmentHandler(gym_factory, seed + 1)
    obs_size, action_size, max_action = env.get_env_specs()

    behavior_net = nn.Sequential(nn.Linear(obs_size, hidden_size), nn.ReLU(), nn.Linear(hidden_size, action_size)).to(
        device)
    optimizer = torch.optim.Adam(behavior_net.parameters(), lr)

    target_net = deepcopy(behavior_net).to(device)

    eps_greedy = EpsilonGreedyPolicy(epsilon_start=epsilon, epsilon_final=0.05,epsilon_decay=50000)

    buffer = ReplayBuffer(spec, max_buffer_size, batch_size)
    collector = DataCollectionProcessor(behavior_net, env, buffer, eps_greedy, factory, device)
    train_process = TrainProcessor(buffer, behavior_net, target_net, optimizer, gamma, max_norm, warmup_steps, device)
    sync_process = SyncProcessor(behavior_net, target_net, tau, sync_freq)

    for step in range(max_steps):
        metrics = {}
        metrics_data = collector.run()
        metrics_train = train_process.run()
        metrics = met
        sync_process.run()

        if metrics and step % 400 == 0:
            log_data = {"charts/epsilon": eps_greedy.epsilon}
            metrics["charts/SPS"] = int(step / (time.time() - start_time))
            metrics["charts/epsilon"] = collector.epsilon_greedy.epsilon
            wandb.log(metrics, step=step)
        if step % 10_000 == 0 and step > warmup_steps:
            avg_score = evaluate_policy(behavior_net, eval_env, episodes=5, device=device)
            wandb.log({"charts/eval_avg_score": avg_score}, step=step)
        wandb.log(metrics, step=step)
if __name__ == '__main__':
    main()
