from copy import deepcopy

import torch
from torch import nn

from backend.ActionValue.DQN.src.ActionHandler import EpsilonGreedyPolicy
from backend.ActionValue.DQN.src.DataCollectionProcessor import DataCollectionProcessor
from backend.ActionValue.DQN.src.TrainProcessor import TrainProcessor
from backend.CommonModels.src import BehaviourAtariDQN
from backend.Utils.src.BatchTransitioner import TransitionSpec, TransitionFactory
from backend.Utils.src.EnvFactory import GymEnvFactory, AtariEnvFactory
from backend.Utils.src.EnviromentHandler import EnvironmentHandler
from backend.Utils.src.ReplayBuffer import ReplayBuffer
from backend.Utils.src.SyncProcessor import SyncProcessor
from backend.CommonModels.src.BehaviourAtariDQN import BehaviourAtariDQN
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def evaluate_policy(policy, env_handler, episodes=5, device="cpu"):
    """
   Eval Function Generated by UNi LLM To be deleted later
    """
    policy.eval()
    total_reward = 0.0

    for _ in range(episodes):
        state = env_handler.reset()
        done = False
        episode_reward = 0.0
        steps = 0

        while not done:
            state_tensor = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)
            with torch.no_grad():
                q_values = policy(state_tensor)
                action = torch.argmax(q_values, dim=1).item()

            next_state, reward, done, _ = env_handler.step(action)
            episode_reward += reward
            state = next_state
            steps += 1

        total_reward += episode_reward

    policy.train()
    return total_reward / episodes

def main():
    # initialization
    lr = 2.5e-4
    epsilon = 1.0
    env_name = "BreakoutNoFrameskip-v4"
    sync_freq = 1000
    hidden_size = 32
    batch_size =64
    max_buffer_size = 1000000
    tau = 1.0
    gamma = 0.99
    max_steps = 1000000
    spec = TransitionSpec(["state", "action", "reward", "next_state", "done"])
    gym_factory = AtariEnvFactory(env_name)
    factory = TransitionFactory(spec)
    seed = 2

    env = EnvironmentHandler(gym_factory, seed)
    eval_env = EnvironmentHandler(gym_factory, seed + 1)
    obs_size, action_size, max_action = env.get_env_specs()

    behavior_net = BehaviourAtariDQN(action_size).to(device)
    optimizer = torch.optim.Adam(behavior_net.parameters(), lr=1e-4)

    target_net = deepcopy(behavior_net).to(device)

    buffer = ReplayBuffer(spec, max_buffer_size, batch_size)
    collector = DataCollectionProcessor(behavior_net, env, buffer, EpsilonGreedyPolicy(epsilon), factory, device)
    train_process = TrainProcessor(buffer, behavior_net, target_net, optimizer, gamma, device)
    sync_process = SyncProcessor(behavior_net, target_net, tau, sync_freq)

    for step in range(max_steps):
        collector.run()
        if step % 4 == 0:
            train_process.run()
        sync_process.run()
        if step % 10_000 == 0 and step > 50_000:
            avg_score = evaluate_policy(behavior_net, eval_env, episodes=5, device=device)
            print(f"[Eval @ step {step}] Average score: {avg_score}")

if __name__ == '__main__':
    main()
